### ISSUE TITLE
Pull connected elements into the group visualization

### ISSUE THREAD

**Issue by julianu** [PRIDE-Toolsuite/pride-inspector#26]
To make more of the visualization, pulling in all connected elements from within the file (like building a real "PIA cluster") would be useful. At the moment only the elements, which are within the reported ProteinAmbiguityGroup, are shown in the visualization.

**Comment by ypriverol** [comment]
Do we have something here

**Comment by julianu** [comment]
Not yet, will implement it later.
But i find this a very interesting feature then.

**Comment by ypriverol** [comment]
Close
