### ISSUE TITLE
Show progress of protein inference

### ISSUE THREAD

**Issue by julianu** [PRIDE-Toolsuite/pride-inspector#44]
For most inferences, it is possible to give a rough estimation of the progress.
This might not be linear in time, but in calculated groups. But this is more or less normal in progress bars etc. I guess.
If we should add something like this, please give a comment here.

**Comment by ypriverol** [comment]
Lets this issue open for a while because we don't have progress bar in any other component on PRIDE Inspector, if the reviewers or the end users compains about that we should adress this issue. We have similar issue with PRIDE charts.

**Comment by ypriverol** [comment]
+1 Closed problem solved
