### ISSUE TITLE
Decoy report understanding

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Toolsuite/pride-inspector#46]
Decoy protein and peptide hits only show numbers. It would be nice to also have a percentage. Additionally, it's unclear to me whether the number of target / decoy identifications also depends on the identification rank. Selecting a different rank to be displayed in the peptide view doesn't change anything.

**Comment by ruiwanguk** [comment]
Changed the numbers to percentage, also aligned peptide ranking filter with decoy filter so they perform consistently.
