### ISSUE TITLE
Peak Intensity Distribution Options

### ISSUE THREAD

**Issue by DarioS** [PRIDE-Toolsuite/pride-inspector#53]
The numeric bins of the intensity summary chart are fixed. The graph has too much whitespace when all of the distribution is in a couple of the bins. Chart Options should have the flexibility to specify the number of bins and their boundaries.

**Comment by ypriverol** [comment]
@DarioS Can you contribute here?

**Comment by DarioS** [comment]
I could, but not until early in next year.

**Comment by ypriverol** [comment]
@DarioS Can you work in this task? We would like to have this feature.

**Comment by DarioS** [comment]
No, I have to work longer than planned on my PhD thesis because of some unexpected setbacks.
