### ISSUE TITLE
pom.xml can't find SNAPSHOT dependencies

### ISSUE THREAD

**Issue by epoyraz** [PRIDE-Toolsuite/pride-inspector#57]
Importing the project results to errors in the pom.xml.
http://i.imgur.com/sMRwGuS.png

Workaroud:
changing the to the lower version worked for me :+1: 
e.g.:
        <inspector-mzgraph-browser.version>2.0.2-SNAPSHOT</inspector-mzgraph-browser.version>
to 
        <inspector-mzgraph-browser.version>2.0.1</inspector-mzgraph-browser.version>

It seem the corresponding SNAPSHOT does not exist :
http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo-snapshots/uk/ac/ebi/pride/toolsuite/inspector-mzgraph-browser/

**Comment by ypriverol** [comment]
@epoyraz you can make the change and propose a pull-request, I will be more than happy to review it and accept your changes. It can be because we did some changes and not release them. Please do the changes and we will do the merge.
