### ISSUE TITLE
Missing method :  getNumberOfMissingSpectra() in ScanExperimentTask.java

### ISSUE THREAD

**Issue by epoyraz** [PRIDE-Toolsuite/pride-inspector#60]
The only error i get now is : 
`missingSpectrumLinks = controller.getNumberOfMissingSpectra();`

the method getNumberOfMissingSpectra() seems to be missing. I assume it is present in one of the  SNAPSHOTs.

**Comment by ypriverol** [comment]
@epoyraz I guess the best way is to download the latest version of ms-data-core-api and compile it, because the latest version should contain this method.

**Comment by epoyraz** [comment]
Looking at http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/uk/ac/ebi/pride/utilities/ms-data-core-api/

it seems 2.0.5 is missing but 2.0.6 is present. In the pom.xml i had changed it to 2.0.4 ... 
Pull request coming.

Thanks !
