### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by gaiazaff** [PRIDE-Toolsuite/pride-inspector#67]
Searching PRIDE Archive works, but when trying to download a dataset, nothing happens.
In the notifications I get:

Unexpected Exception
java.lang.NoClassDefFoundError: com/asperasoft/faspmanager/TransferListener

I am on Windows

**Comment by ypriverol** [comment]
Can you try this version: https://github.com/PRIDE-Toolsuite/pride-inspector/releases/download/pride-inspector-2.5.3/pride-inspector-2.5.3.zip

**Comment by gaiazaff** [comment]
Thanks, this version is working.
