### ISSUE TITLE
Unable to build PRIDE Inspector - missing profiles?

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Toolsuite/pride-inspector#69]
I'm unable to build PRIDE Inspector. It appears that the following dependnecies (at least) are missing:
-  pi-desktop-build
-  env-public
Taken from the POM:

>   To build desktop version, you need
>         mvn -P pi-desktop-build,env-public clean package

Do you have access to these profiles, @ypriverol ?

**Comment by ypriverol** [comment]
I have. But I think these profiles are related to the Java Web Start. I will check them and let you know.

**Comment by ypriverol** [comment]
I have fixed this error. I will update soon the code.

**Comment by ypriverol** [comment]
Solve here: https://github.com/PRIDE-Toolsuite/pride-inspector/releases/tag/pride-inspector-2.5.4
